# Generated by Django 3.2.16 on 2022-12-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('status', models.TextField(null=True)),
                ('total_amount', models.BigIntegerField(null=True)),
                ('discount_amount', models.IntegerField(null=True)),
                ('discount_percentage', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('merchant_network_id', models.TextField(null=True)),
                ('merchant_category', models.TextField(null=True)),
            ],
        ),
    ]
