# Generated by Django 3.2.16 on 2022-12-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_load_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='flagged_reason',
            field=models.TextField(null=True),
        ),
    ]
