const dummyProducts = [{
    provider_name: 'Bird',	
    name: 'Scoot 1',
    mode_type: 'Escooter',	
    fleet_partner: true,
    transaction_name: 'Bird buy',
    discount_amount: 10,
    discount_description: 'Fleet users receiev 10% discount on purchase of the Bird Scoot 1 e-scooter.',
    country: 'US',
    metro_area: 'NationWide',
    merchant_network_id: '000445266622999',
    merchant_category: 'miscellaneous_recreation_services',
    pricing_type: 'FLAT',
    pricing_unit: 'one-time',
    pricing_amount: '2,299.00',
    website_url: 'https://www.bird.co/',
    icon_url: 'https://static.movewithfleet.com/assets/provider_images/collected_defaults/bird/primary.png',
    description: 'Bird provides eco-friendly transporation for everyone through their e-scooter sharing app and options to buy e-scooters and e-bikes.',
    setup_instructions: 'https://www.bird.co/how/',
    refund_policies: 'https://shop.bird.co/pages/refund-policy',
    show_user: true,
    coming_soon: false,
    rovider_support: 'https://help.bird.co/hc/en-us',
    support_phone_number: '1-866-205-2442',
    support_email: 'hello@bird.co'
},{
    provider_name: 'Bird',	
    name: 'Scoot 1',
    mode_type: 'Escooter',	
    fleet_partner: true,
    transaction_name: 'Bird buy',
    discount_amount: 10,
    discount_description: 'Fleet users receiev 10% discount on purchase of the Bird Scoot 1 e-scooter.',
    country: 'US',
    metro_area: 'NationWide',
    merchant_network_id: '000445266622999',
    merchant_category: 'miscellaneous_recreation_services',
    pricing_type: 'FLAT',
    pricing_unit: 'one-time',
    pricing_amount: '2,299.00',
    website_url: 'https://www.bird.co/',
    icon_url: 'https://static.movewithfleet.com/assets/provider_images/collected_defaults/bird/primary.png',
    description: 'Bird provides eco-friendly transporation for everyone through their e-scooter sharing app and options to buy e-scooters and e-bikes.',
    setup_instructions: 'https://www.bird.co/how/',
    refund_policies: 'https://shop.bird.co/pages/refund-policy',
    show_user: true,
    coming_soon: false,
    rovider_support: 'https://help.bird.co/hc/en-us',
    support_phone_number: '1-866-205-2442',
    support_email: 'hello@bird.co'
},{
    provider_name: 'Bird',	
    name: 'Scoot 1',
    mode_type: 'Escooter',	
    fleet_partner: true,
    transaction_name: 'Bird buy',
    discount_amount: 10,
    discount_description: 'Fleet users receiev 10% discount on purchase of the Bird Scoot 1 e-scooter.',
    country: 'US',
    metro_area: 'NationWide',
    merchant_network_id: '000445266622999',
    merchant_category: 'miscellaneous_recreation_services',
    pricing_type: 'FLAT',
    pricing_unit: 'one-time',
    pricing_amount: '2,299.00',
    website_url: 'https://www.bird.co/',
    icon_url: 'https://static.movewithfleet.com/assets/provider_images/collected_defaults/bird/primary.png',
    description: 'Bird provides eco-friendly transporation for everyone through their e-scooter sharing app and options to buy e-scooters and e-bikes.',
    setup_instructions: 'https://www.bird.co/how/',
    refund_policies: 'https://shop.bird.co/pages/refund-policy',
    show_user: true,
    coming_soon: false,
    rovider_support: 'https://help.bird.co/hc/en-us',
    support_phone_number: '1-866-205-2442',
    support_email: 'hello@bird.co'
},{
    provider_name: 'Bird',	
    name: 'Scoot 1',
    mode_type: 'Escooter',	
    fleet_partner: true,
    transaction_name: 'Bird buy',
    discount_amount: 10,
    discount_description: 'Fleet users receiev 10% discount on purchase of the Bird Scoot 1 e-scooter.',
    country: 'US',
    metro_area: 'NationWide',
    merchant_network_id: '000445266622999',
    merchant_category: 'miscellaneous_recreation_services',
    pricing_type: 'FLAT',
    pricing_unit: 'one-time',
    pricing_amount: '2,299.00',
    website_url: 'https://www.bird.co/',
    icon_url: 'https://static.movewithfleet.com/assets/provider_images/collected_defaults/bird/primary.png',
    description: 'Bird provides eco-friendly transporation for everyone through their e-scooter sharing app and options to buy e-scooters and e-bikes.',
    setup_instructions: 'https://www.bird.co/how/',
    refund_policies: 'https://shop.bird.co/pages/refund-policy',
    show_user: true,
    coming_soon: false,
    rovider_support: 'https://help.bird.co/hc/en-us',
    support_phone_number: '1-866-205-2442',
    support_email: 'hello@bird.co'
},{
    provider_name: 'Bird',	
    name: 'Scoot 1',
    mode_type: 'Escooter',	
    fleet_partner: true,
    transaction_name: 'Bird buy',
    discount_amount: 10,
    discount_description: 'Fleet users receiev 10% discount on purchase of the Bird Scoot 1 e-scooter.',
    country: 'US',
    metro_area: 'NationWide',
    merchant_network_id: '000445266622999',
    merchant_category: 'miscellaneous_recreation_services',
    pricing_type: 'FLAT',
    pricing_unit: 'one-time',
    pricing_amount: '2,299.00',
    website_url: 'https://www.bird.co/',
    icon_url: 'https://static.movewithfleet.com/assets/provider_images/collected_defaults/bird/primary.png',
    description: 'Bird provides eco-friendly transporation for everyone through their e-scooter sharing app and options to buy e-scooters and e-bikes.',
    setup_instructions: 'https://www.bird.co/how/',
    refund_policies: 'https://shop.bird.co/pages/refund-policy',
    show_user: true,
    coming_soon: false,
    rovider_support: 'https://help.bird.co/hc/en-us',
    support_phone_number: '1-866-205-2442',
    support_email: 'hello@bird.co'
},{
    provider_name: 'Bird',	
    name: 'Scoot 1',
    mode_type: 'Escooter',	
    fleet_partner: true,
    transaction_name: 'Bird buy',
    discount_amount: 10,
    discount_description: 'Fleet users receiev 10% discount on purchase of the Bird Scoot 1 e-scooter.',
    country: 'US',
    metro_area: 'NationWide',
    merchant_network_id: '000445266622999',
    merchant_category: 'miscellaneous_recreation_services',
    pricing_type: 'FLAT',
    pricing_unit: 'one-time',
    pricing_amount: '2,299.00',
    website_url: 'https://www.bird.co/',
    icon_url: 'https://static.movewithfleet.com/assets/provider_images/collected_defaults/bird/primary.png',
    description: 'Bird provides eco-friendly transporation for everyone through their e-scooter sharing app and options to buy e-scooters and e-bikes.',
    setup_instructions: 'https://www.bird.co/how/',
    refund_policies: 'https://shop.bird.co/pages/refund-policy',
    show_user: true,
    coming_soon: false,
    rovider_support: 'https://help.bird.co/hc/en-us',
    support_phone_number: '1-866-205-2442',
    support_email: 'hello@bird.co'
},{
    provider_name: 'Bird',	
    name: 'Scoot 1',
    mode_type: 'Escooter',	
    fleet_partner: true,
    transaction_name: 'Bird buy',
    discount_amount: 10,
    discount_description: 'Fleet users receiev 10% discount on purchase of the Bird Scoot 1 e-scooter.',
    country: 'US',
    metro_area: 'NationWide',
    merchant_network_id: '000445266622999',
    merchant_category: 'miscellaneous_recreation_services',
    pricing_type: 'FLAT',
    pricing_unit: 'one-time',
    pricing_amount: '2,299.00',
    website_url: 'https://www.bird.co/',
    icon_url: 'https://static.movewithfleet.com/assets/provider_images/collected_defaults/bird/primary.png',
    description: 'Bird provides eco-friendly transporation for everyone through their e-scooter sharing app and options to buy e-scooters and e-bikes.',
    setup_instructions: 'https://www.bird.co/how/',
    refund_policies: 'https://shop.bird.co/pages/refund-policy',
    show_user: true,
    coming_soon: false,
    rovider_support: 'https://help.bird.co/hc/en-us',
    support_phone_number: '1-866-205-2442',
    support_email: 'hello@bird.co'
},{
    provider_name: 'Bird',	
    name: 'Scoot 1',
    mode_type: 'Escooter',	
    fleet_partner: true,
    transaction_name: 'Bird buy',
    discount_amount: 10,
    discount_description: 'Fleet users receiev 10% discount on purchase of the Bird Scoot 1 e-scooter.',
    country: 'US',
    metro_area: 'NationWide',
    merchant_network_id: '000445266622999',
    merchant_category: 'miscellaneous_recreation_services',
    pricing_type: 'FLAT',
    pricing_unit: 'one-time',
    pricing_amount: '2,299.00',
    website_url: 'https://www.bird.co/',
    icon_url: 'https://static.movewithfleet.com/assets/provider_images/collected_defaults/bird/primary.png',
    description: 'Bird provides eco-friendly transporation for everyone through their e-scooter sharing app and options to buy e-scooters and e-bikes.',
    setup_instructions: 'https://www.bird.co/how/',
    refund_policies: 'https://shop.bird.co/pages/refund-policy',
    show_user: true,
    coming_soon: false,
    rovider_support: 'https://help.bird.co/hc/en-us',
    support_phone_number: '1-866-205-2442',
    support_email: 'hello@bird.co'
},{
    provider_name: 'Bird',	
    name: 'Scoot 1',
    mode_type: 'Escooter',	
    fleet_partner: true,
    transaction_name: 'Bird buy',
    discount_amount: 10,
    discount_description: 'Fleet users receiev 10% discount on purchase of the Bird Scoot 1 e-scooter.',
    country: 'US',
    metro_area: 'NationWide',
    merchant_network_id: '000445266622999',
    merchant_category: 'miscellaneous_recreation_services',
    pricing_type: 'FLAT',
    pricing_unit: 'one-time',
    pricing_amount: '2,299.00',
    website_url: 'https://www.bird.co/',
    icon_url: 'https://static.movewithfleet.com/assets/provider_images/collected_defaults/bird/primary.png',
    description: 'Bird provides eco-friendly transporation for everyone through their e-scooter sharing app and options to buy e-scooters and e-bikes.',
    setup_instructions: 'https://www.bird.co/how/',
    refund_policies: 'https://shop.bird.co/pages/refund-policy',
    show_user: true,
    coming_soon: false,
    rovider_support: 'https://help.bird.co/hc/en-us',
    support_phone_number: '1-866-205-2442',
    support_email: 'hello@bird.co'
}]

export default dummyProducts

